spring:
  application:
    name:
      studentService
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring-boot.application.instance_id:${random.value}}}

server:
  port: 0

